extern "C" const char* const ITEM_DESC_TABLE_A[64] = {
    /*  0 SMALL_RECOVERY    */ "Restores 500 HP. Cheap, stackable; throwable in battle.",
    /*  1 MEDIUM_RECOVERY   */ "Restores 1500 HP. Solid mid-tier heal.",
    /*  2 LARGE_RECOVERY    */ "Restores 5000 HP.",
    /*  3 SUPER_RECOVERY    */ "Restores HP to maximum. Save for ultimate-tier fights.",
    /*  4 MP_FLOPPY         */ "Restores 500 MP. Useful for spell-heavy partners.",
    /*  5 MEDIUM_MP         */ "Restores 1500 MP.",
    /*  6 LARGE_MP          */ "Restores 5000 MP.",
    /*  7 DOUBLE_FLOPPY     */ "Restores 1500 HP and 1500 MP at once. Saves a slot.",
    /*  8 VARIOUS           */ "Removes every status effect (poison, paralysis, sleep, etc.).",
    /*  9 OMNIPOTENT        */ "Heals 1500 HP/MP and removes every status condition.",
    /* 10 PROTECTION        */ "One-shot ward. Blocks the next hit your partner takes.",
    /* 11 RESTORE           */ "Heals 50% of max HP. Revives a KO'd Digimon.",
    /* 12 SUPER_RESTORE     */ "Heals to full HP, cures status, revives KO'd partner.",
    /* 13 BANDAGE           */ "Always cures injury. 20% chance to also clear sickness.",
    /* 14 MEDICINE          */ "Always cures both injury and sickness.",
    /* 15 OFFENSE_DISK      */ "+20 OFF, capped at 130% of base.",
    /* 16 DEFENSE_DISK      */ "+20 DEF, capped at 130% of base.",
    /* 17 SPEED_DISK        */ "+20 SPD, capped at 130% of base.",
    /* 18 OMNI_DISK         */ "+20 OFF/DEF/SPD. Not subject to the 130% per-stat cap.",
    /* 19 SUPER_OFFENSE_DISK*/ "+50 OFF, capped at 130% of base.",
    /* 20 SUPER_DEFENSE_DISK*/ "+50 DEF, capped at 130% of base.",
    /* 21 SUPER_SPEED_DISK  */ "+50 SPD, capped at 130% of base.",
    /* 22 AUTOPILOT         */ "Auto-walks your partner back to File City.",
    /* 23 OFFENSE_CHIP      */ "Permanent +50 OFF. Cap 999. Stacks across uses.",
    /* 24 DEFENSE_CHIP      */ "Permanent +50 DEF. Cap 999.",
    /* 25 BRAIN_SHIP        */ "Permanent +50 BRAIN. Cap 999.",
    /* 26 SPEED_CHIP        */ "Permanent +50 SPD. Cap 999.",
    /* 27 HP_CHIP           */ "Permanent +500 max HP. Cap 9999.",
    /* 28 MP_CHIP           */ "Permanent +500 max MP. Cap 9999.",
    /* 29 DV_CHIP_A         */ "+100 OFF, +100 BRAIN. Costs -24h lifetime and -1 of 10 tamer levels.",
    /* 30 DV_CHIP_D         */ "+100 DEF, +100 SPD. Costs -24h lifetime and -1 of 10 tamer levels.",
    /* 31 DV_CHIP_E         */ "+1000 max HP, +1000 max MP. Costs -24h lifetime and -1 of 10 tamer levels.",
    /* 32 PORTA_POTTY       */ "Cleans the partner instantly. Resets poop timer.",
    /* 33 TRAINING_MANUAL   */ "Passive: improves training session results.",
    /* 34 REST_PILLOW       */ "Passive: sleep recovery x1.2.",
    /* 35 ENEMY_REPEL       */ "Passive: +20 to enemy flee roll. Fewer encounters.",
    /* 36 ENEMY_BELL        */ "Passive: -50 to enemy flee roll. More encounters.",
    /* 37 HEALTH_SHOE       */ "Passive: +5 HP/MP every ~20 frames while walking.",
    /* 38 MEAT              */ "Energy +12, weight +1. Basic meal.",
    /* 39 GIANT_MEAT        */ "Energy +24, weight +2.",
    /* 40 SIRLOIN           */ "Energy +35, tired -5, happy +3, weight +3.",
    /* 41 SUPERCARROT       */ "Energy +10, weight -2. Boosts SPD training 6h.",
    /* 42 HAWK_RADISH       */ "Energy +15, weight +3. Boosts OFF training 6h.",
    /* 43 SPINY_GREEN       */ "Energy +9, tired -50, weight +1.",
    /* 44 DIGIMUSHROOM      */ "Energy +12, weight +1.",
    /* 45 ICE_MUSHROOM      */ "Energy +19, discipline +50, weight +2.",
    /* 46 DELUXE_MUSHROOM   */ "Permanent +100 max HP/MP and +10 to all combat stats. Energy +38, weight +4.",
    /* 47 DIGIPINE          */ "Energy +22, weight +2. Boosts ALL training 6h.",
    /* 48 BLUE_APPLE        */ "Energy +30, happy +50, weight +3.",
    /* 49 RED_BERRY         */ "Energy +25, tired -20, happy +20, discipline +20, weight +2.",
    /* 50 GOLD_ACORN        */ "Energy +40, weight +4.",
    /* 51 BIG_BERRY         */ "Energy +100, weight +10. Huge weight gain.",
    /* 52 SWEET_NUT         */ "Heals HP to full. Energy +20, weight +2.",
    /* 53 SUPER_VEGGY       */ "Heals MP to full. Energy +16, weight +2.",
    /* 54 PRICKLYPEAR       */ "Energy +33, weight -5. Slimming food.",
    /* 55 ORANGE_BANANA     */ "Heals 1000 HP and 1000 MP. Energy +24, weight +2.",
    /* 56 POWER_FRUIT       */ "Permanent +20 OFF. Energy +20, weight +2.",
    /* 57 POWER_ICE         */ "Permanent +20 DEF. Energy +20, weight +2.",
    /* 58 SPEED_LEAF        */ "Permanent +20 SPD. Energy +20, weight +2.",
    /* 59 SAGE_FRUIT        */ "Permanent +20 BRAIN. Energy +20, weight +2.",
    /* 60 MUSCLE_YAM        */ "Permanent +200 max HP. Energy +20, weight +2.",
    /* 61 CALM_BERRY        */ "Permanent +200 max MP. Energy +20, weight +2.",
    /* 62 DIGIANCHOVY       */ "Energy +8, weight +1. Caught with the basic rod.",
    /* 63 DIGISNAPPER       */ "Energy +12, weight +1.",
};
