#include "ItemInfo.hpp"

namespace
{
    struct ItemHeader
    {
        const char* headline;
        const char* detail;
    };

    constexpr ItemHeader FALLBACK_HEADER = {"Item", ""};

    // Indexed by ItemType numeric value (0..127).
    constexpr ItemHeader HEADER_TABLE[128] = {
        /*  0 SMALL_RECOVERY    */ {"Heal 500 HP",         "Use anywhere"},
        /*  1 MEDIUM_RECOVERY   */ {"Heal 1500 HP",        "Use anywhere"},
        /*  2 LARGE_RECOVERY    */ {"Heal 5000 HP",        "Use anywhere"},
        /*  3 SUPER_RECOVERY    */ {"Full HP heal",        "Use anywhere"},
        /*  4 MP_FLOPPY         */ {"Heal 500 MP",         "Use anywhere"},
        /*  5 MEDIUM_MP         */ {"Heal 1500 MP",        "Use anywhere"},
        /*  6 LARGE_MP          */ {"Heal 5000 MP",        "Use anywhere"},
        /*  7 DOUBLE_FLOPPY     */ {"Heal 1500 HP/MP",     "Use anywhere"},
        /*  8 VARIOUS           */ {"Cure status",         "Use anywhere"},
        /*  9 OMNIPOTENT        */ {"Heal+Cure 1500",      "Use anywhere"},
        /* 10 PROTECTION        */ {"Block 1 attack",      "Use in battle"},
        /* 11 RESTORE           */ {"Revive +50% HP",      "Use in battle"},
        /* 12 SUPER_RESTORE     */ {"Revive full",         "Use in battle"},
        /* 13 BANDAGE           */ {"Cure injury",         "Use to raise"},
        /* 14 MEDICINE          */ {"Cure injury+sick",    "Use to raise"},
        /* 15 OFFENSE_DISK      */ {"+20 OFF",             "Use in battle"},
        /* 16 DEFENSE_DISK      */ {"+20 DEF",             "Use in battle"},
        /* 17 SPEED_DISK        */ {"+20 SPD",             "Use in battle"},
        /* 18 OMNI_DISK         */ {"+20 OFF/DEF/SPD",     "Use in battle"},
        /* 19 SUPER_OFFENSE_DISK*/ {"+50 OFF",             "Use in battle"},
        /* 20 SUPER_DEFENSE_DISK*/ {"+50 DEF",             "Use in battle"},
        /* 21 SUPER_SPEED_DISK  */ {"+50 SPD",             "Use in battle"},
        /* 22 AUTOPILOT         */ {"Autopilot",           "Use anywhere"},
        /* 23 OFFENSE_CHIP      */ {"+50 OFF perm",        "Use to raise"},
        /* 24 DEFENSE_CHIP      */ {"+50 DEF perm",        "Use to raise"},
        /* 25 BRAIN_SHIP        */ {"+50 BRAIN perm",      "Use to raise"},
        /* 26 SPEED_CHIP        */ {"+50 SPD perm",        "Use to raise"},
        /* 27 HP_CHIP           */ {"+500 max HP",         "Use to raise"},
        /* 28 MP_CHIP           */ {"+500 max MP",         "Use to raise"},
        /* 29 DV_CHIP_A         */ {"+100 OFF/BRAIN",      "Use to raise"},
        /* 30 DV_CHIP_D         */ {"+100 DEF/SPD",        "Use to raise"},
        /* 31 DV_CHIP_E         */ {"+1000 max HP/MP",     "Use to raise"},
        /* 32 PORTA_POTTY       */ {"Clear poop",          "Use to raise"},
        /* 33 TRAINING_MANUAL   */ {"Training boon",       "Hold in inventory"},
        /* 34 REST_PILLOW       */ {"Better sleep",        "Hold in inventory"},
        /* 35 ENEMY_REPEL       */ {"Fewer fights",        "Hold in inventory"},
        /* 36 ENEMY_BELL        */ {"More fights",         "Hold in inventory"},
        /* 37 HEALTH_SHOE       */ {"Heal walking",        "Hold in inventory"},
        /* 38 MEAT              */ {"Food",                "Feed to raise"},
        /* 39 GIANT_MEAT        */ {"Food",                "Feed to raise"},
        /* 40 SIRLOIN           */ {"Food",                "Feed to raise"},
        /* 41 SUPERCARROT       */ {"Food, train aid",     "Feed to raise"},
        /* 42 HAWK_RADISH       */ {"Food, train aid",     "Feed to raise"},
        /* 43 SPINY_GREEN       */ {"Food",                "Feed to raise"},
        /* 44 DIGIMUSHROOM      */ {"Food",                "Feed to raise"},
        /* 45 ICE_MUSHROOM      */ {"Food",                "Feed to raise"},
        /* 46 DELUXE_MUSHROOM   */ {"+100 HP/MP +10 all",  "Feed to raise"},
        /* 47 DIGIPINE          */ {"Food, train aid",     "Feed to raise"},
        /* 48 BLUE_APPLE        */ {"Food",                "Feed to raise"},
        /* 49 RED_BERRY         */ {"Food",                "Feed to raise"},
        /* 50 GOLD_ACORN        */ {"Food",                "Feed to raise"},
        /* 51 BIG_BERRY         */ {"Big food",            "Feed to raise"},
        /* 52 SWEET_NUT         */ {"Food, full HP",       "Feed to raise"},
        /* 53 SUPER_VEGGY       */ {"Food, full MP",       "Feed to raise"},
        /* 54 PRICKLYPEAR       */ {"Food, slim",          "Feed to raise"},
        /* 55 ORANGE_BANANA     */ {"Food, big heal",      "Feed to raise"},
        /* 56 POWER_FRUIT       */ {"+20 OFF perm",        "Feed to raise"},
        /* 57 POWER_ICE         */ {"+20 DEF perm",        "Feed to raise"},
        /* 58 SPEED_LEAF        */ {"+20 SPD perm",        "Feed to raise"},
        /* 59 SAGE_FRUIT        */ {"+20 BRAIN perm",      "Feed to raise"},
        /* 60 MUSCLE_YAM        */ {"+200 max HP",         "Feed to raise"},
        /* 61 CALM_BERRY        */ {"+200 max MP",         "Feed to raise"},
        /* 62 DIGIANCHOVY       */ {"Fish",                "Feed to raise"},
        /* 63 DIGISNAPPER       */ {"Fish",                "Feed to raise"},
        /* 64 DIGITROUT         */ {"Fish",                "Feed to raise"},
        /* 65 BLACK_TROUT       */ {"+10 HP/MP, +1 all",   "Feed to raise"},
        /* 66 DIGICATFISH       */ {"Fish",                "Feed to raise"},
        /* 67 DIGISEABASS       */ {"Fish, full heal",     "Feed to raise"},
        /* 68 MOLDY_MEAT        */ {"Spoiled food",        "Feed to raise"},
        /* 69 HAPPYMUSHROOM     */ {"Risky food",          "Feed to raise"},
        /* 70 CHAIN_MELON       */ {"Premium food",        "Feed to raise"},
        /* 71 GREY_CLAWS        */ {"Digivolution Item",   ""},
        /* 72 FIREBALL          */ {"Digivolution Item",   ""},
        /* 73 FLAMEWING         */ {"Digivolution Item",   ""},
        /* 74 IRON_HOOF         */ {"Digivolution Item",   ""},
        /* 75 MONO_STONE        */ {"Digivolution Item",   ""},
        /* 76 STEEL_DRILL       */ {"Digivolution Item",   ""},
        /* 77 WHITE_FANG        */ {"Digivolution Item",   ""},
        /* 78 BLACK_WING        */ {"Digivolution Item",   ""},
        /* 79 SPIKE_CLUB        */ {"Digivolution Item",   ""},
        /* 80 FLAMEINGMANE      */ {"Digivolution Item",   ""},
        /* 81 WHITE_WING        */ {"Digivolution Item",   ""},
        /* 82 TORN_TATTER       */ {"Digivolution Item",   ""},
        /* 83 ELECTRO_RING      */ {"Digivolution Item",   "No valid target"},
        /* 84 RAINBOWHORN       */ {"Digivolution Item",   ""},
        /* 85 ROOSTER           */ {"Digivolution Item",   ""},
        /* 86 UNIHORN           */ {"Digivolution Item",   ""},
        /* 87 HORN_HELMET       */ {"Digivolution Item",   ""},
        /* 88 SCISSOR_JAW       */ {"Digivolution Item",   ""},
        /* 89 FERTILIZER        */ {"Digivolution Item",   ""},
        /* 90 KOGA_LAWS         */ {"Digivolution Item",   ""},
        /* 91 WATERBOTTLE       */ {"Digivolution Item",   ""},
        /* 92 NORTH_STAR        */ {"Digivolution Item",   ""},
        /* 93 RED_SHELL         */ {"Digivolution Item",   ""},
        /* 94 HARD_SCALE        */ {"Digivolution Item",   ""},
        /* 95 BLUECRYSTAL       */ {"Digivolution Item",   ""},
        /* 96 ICE_CRYSTAL       */ {"Digivolution Item",   ""},
        /* 97 HAIR_GROWER       */ {"Digivolution Item",   ""},
        /* 98 SUNGLASSES        */ {"Digivolution Item",   ""},
        /* 99 METAL_PART        */ {"Digivolution Item",   ""},
        /*100 FATAL_BONE        */ {"Digivolution Item",   ""},
        /*101 CYBER_PART        */ {"Digivolution Item",   ""},
        /*102 MEGA_HAND         */ {"Digivolution Item",   ""},
        /*103 SILVER_BALL       */ {"Digivolution Item",   ""},
        /*104 METAL_ARMOR       */ {"Digivolution Item",   ""},
        /*105 CHAINSAW          */ {"Digivolution Item",   ""},
        /*106 SMALL_SPEAR       */ {"Digivolution Item",   ""},
        /*107 X_BANDAGE         */ {"Digivolution Item",   ""},
        /*108 RAY_GUN           */ {"Digivolution Item",   ""},
        /*109 GOLD_BANANA       */ {"Digivolution Item",   ""},
        /*110 MYSTY_EGG         */ {"Digivolution Item",   ""},
        /*111 RED_RUBY          */ {"Digivolution Item",   ""},
        /*112 BETTLEPEARL       */ {"Digivolution Item",   ""},
        /*113 CORAL_CHARM       */ {"Digivolution Item",   ""},
        /*114 MOON_MIRROR       */ {"Digivolution Item",   ""},
        /*115 BLUE_FLUTE        */ {"Key item",            "Hold in inventory"},
        /*116 OLD_ROD           */ {"Fishing rod",         "Hold in inventory"},
        /*117 AMAZING_ROD       */ {"Fishing rod",         "Hold in inventory"},
        /*118 LEOMONSTONE       */ {"Key item",            "Quest item"},
        /*119 MANSION_KEY       */ {"Key item",            "Quest item"},
        /*120 GEAR              */ {"Key item",            "Quest item"},
        /*121 RAIN_PLANT        */ {"Food, full MP",       "Feed to raise"},
        /*122 STEAK             */ {"Food, big heal",      "Feed to raise"},
        /*123 FRIDGE_KEY        */ {"Key item",            "Quest item"},
        /*124 AS_DECODER        */ {"Key item",            "Quest item"},
        /*125 GIGA_HAND         */ {"Digivolution Item",   ""},
        /*126 NOBLE_MANE        */ {"Digivolution Item",   ""},
        /*127 METAL_BANANA      */ {"Digivolution Item",   ""},
    };
}

ItemInfo getItemInfo(ItemType type)
{
    const auto idx = static_cast<int>(type);
    if (idx < 0 || idx >= 128)
        return {FALLBACK_HEADER.headline, FALLBACK_HEADER.detail, ""};

    const auto& h    = HEADER_TABLE[idx];
    const char* desc = idx < 64 ? ITEM_DESC_TABLE_A[idx] : ITEM_DESC_TABLE_B[idx - 64];
    return {h.headline, h.detail, desc != nullptr ? desc : ""};
}
