extern "C" const char* const ITEM_DESC_TABLE_B[64] = {
    /* 64 DIGITROUT         */ "Mid-tier fish. Energy +22, weight +2.",
    /* 65 BLACK_TROUT       */ "Rare. Permanent +10 max HP/MP and +1 to OFF/DEF/SPD/BRAIN. Energy +27, weight -2.",
    /* 66 DIGICATFISH       */ "Big catch. Energy +49, weight +5. Heavy weight gain.",
    /* 67 DIGISEABASS       */ "Rare. Heals HP and MP to full. Energy +35, weight +4. 20% sickness chance, +3 days lifetime.",
    /* 68 MOLDY_MEAT        */ "Energy +30, weight +2 - but 100% sickness chance. Use only if you want to keep a partner sick.",
    /* 69 HAPPYMUSHROOM     */ "Energy +15, happiness +30, weight +1. 30% sickness chance - gamble for the happiness.",
    /* 70 CHAIN_MELON       */ "Energy +50, tiredness -50, happy +50, weight +3, +20 days lifetime. 3% sickness chance.",
    /* 71 GREY_CLAWS        */ nullptr,
    /* 72 FIREBALL          */ nullptr,
    /* 73 FLAMEWING         */ nullptr,
    /* 74 IRON_HOOF         */ nullptr,
    /* 75 MONO_STONE        */ nullptr,
    /* 76 STEEL_DRILL       */ nullptr,
    /* 77 WHITE_FANG        */ nullptr,
    /* 78 BLACK_WING        */ nullptr,
    /* 79 SPIKE_CLUB        */ nullptr,
    /* 80 FLAMEINGMANE      */ nullptr,
    /* 81 WHITE_WING        */ nullptr,
    /* 82 TORN_TATTER       */ nullptr,
    /* 83 ELECTRO_RING      */ "This item has no working evolution target in this build.",
    /* 84 RAINBOWHORN       */ nullptr,
    /* 85 ROOSTER           */ nullptr,
    /* 86 UNIHORN           */ nullptr,
    /* 87 HORN_HELMET       */ nullptr,
    /* 88 SCISSOR_JAW       */ nullptr,
    /* 89 FERTILIZER        */ nullptr,
    /* 90 KOGA_LAWS         */ nullptr,
    /* 91 WATERBOTTLE       */ nullptr,
    /* 92 NORTH_STAR        */ nullptr,
    /* 93 RED_SHELL         */ nullptr,
    /* 94 HARD_SCALE        */ nullptr,
    /* 95 BLUECRYSTAL       */ nullptr,
    /* 96 ICE_CRYSTAL       */ nullptr,
    /* 97 HAIR_GROWER       */ nullptr,
    /* 98 SUNGLASSES        */ nullptr,
    /* 99 METAL_PART        */ nullptr,
    /*100 FATAL_BONE        */ nullptr,
    /*101 CYBER_PART        */ nullptr,
    /*102 MEGA_HAND         */ nullptr,
    /*103 SILVER_BALL       */ nullptr,
    /*104 METAL_ARMOR       */ nullptr,
    /*105 CHAINSAW          */ nullptr,
    /*106 SMALL_SPEAR       */ nullptr,
    /*107 X_BANDAGE         */ nullptr,
    /*108 RAY_GUN           */ nullptr,
    /*109 GOLD_BANANA       */ nullptr,
    /*110 MYSTY_EGG         */ nullptr,
    /*111 RED_RUBY          */ nullptr,
    /*112 BETTLEPEARL       */ nullptr,
    /*113 CORAL_CHARM       */ nullptr,
    /*114 MOON_MIRROR       */ nullptr,
    /*115 BLUE_FLUTE        */ "Summons Whamon at the Great Canyon ocean. Required to reach areas across the sea.",
    /*116 OLD_ROD           */ "Basic fishing rod. Catches common fish at any pond.",
    /*117 AMAZING_ROD       */ "Upgraded rod. Higher catch rate and access to rarer fish like Black Trout and Digiseabass.",
    /*118 LEOMONSTONE       */ "Used in the Leomon revival quest to restore his stone form.",
    /*119 MANSION_KEY       */ "Opens the locked door of the Haunted Mansion. Required to progress that questline.",
    /*120 GEAR              */ "Spare part for Andromon's lab. Brings him back online after the factory questline.",
    /*121 RAIN_PLANT        */ "Heals 1000 MP. No food side effects.",
    /*122 STEAK             */ "Heals 1000 HP. Energy +32. 20% sickness chance - use sparingly.",
    /*123 FRIDGE_KEY        */ "Opens the locked fridge in the restaurant. Quest unlock.",
    /*124 AS_DECODER        */ "Ancient Script decoder. Translates ancient runes encountered in late-game areas.",
    /*125 GIGA_HAND         */ nullptr,
    /*126 NOBLE_MANE        */ nullptr,
    /*127 METAL_BANANA      */ nullptr,
};
